sudo: false

language: php

php:
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpstan analyze src -l max
  - vendor/bin/composer-require-checker check
  - vendor/bin/kahlan

notifications:
  email:
    - pasafama@gmail.com
